# Generated by Django 2.2 on 2020-07-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_sell',
            field=models.CharField(default='buyer', max_length=100),
        ),
    ]
