# Generated by Django 2.2 on 2020-07-21 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_user_user_sell'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_sell',
            new_name='user_type',
        ),
    ]
