# Generated by Django 2.2 on 2020-07-31 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20200731_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_category', models.CharField(choices=[('python', 'python'), ('jave', 'java'), ('php', 'php')], default='', max_length=100)),
                ('book_name', models.CharField(max_length=100)),
                ('book_author', models.CharField(max_length=100)),
                ('book_price', models.CharField(max_length=100)),
                ('book_desc', models.TextField()),
                ('book_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
