# Generated by Django 2.2 on 2020-08-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='item',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
